# Generated by Django 5.2.6 on 2025-12-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_duplicate_profile_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client'), ('student', 'Student'), ('worker', 'Worker'), ('professional', 'Professional'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
