# Generated by Django 5.2.6 on 2025-12-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-1 years)'), ('mid', 'Mid Level (2-5 years)'), ('senior', 'Senior Level (6-10 years)'), ('expert', 'Expert Level (10+ years)')], default='entry', max_length=20),
        ),
    ]
