# Generated by Django 5.2.6 on 2025-12-09 06:18

from django.db import migrations


def migrate_experience_levels(apps, schema_editor):
    """
    Migrate old experience level values to new ones:
    - 'intermediate' -> 'mid'
    - 'experienced' -> 'senior'
    """
    ProfessionalProfile = apps.get_model('users', 'ProfessionalProfile')
    
    # Update intermediate to mid
    ProfessionalProfile.objects.filter(experience_level='intermediate').update(experience_level='mid')
    
    # Update experienced to senior
    ProfessionalProfile.objects.filter(experience_level='experienced').update(experience_level='senior')


def reverse_migrate_experience_levels(apps, schema_editor):
    """
    Reverse migration: restore old experience level values
    """
    ProfessionalProfile = apps.get_model('users', 'ProfessionalProfile')
    
    # Reverse: mid to intermediate
    ProfessionalProfile.objects.filter(experience_level='mid').update(experience_level='intermediate')
    
    # Reverse: senior to experienced
    ProfessionalProfile.objects.filter(experience_level='senior').update(experience_level='experienced')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_update_experience_levels'),
    ]

    operations = [
        migrations.RunPython(migrate_experience_levels, reverse_migrate_experience_levels),
    ]
