# Generated by Django 5.2.6 on 2025-12-07 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_review_edit_count'),
        ('requests', '0006_alter_request_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_created', 'New Request'), ('request_accepted', 'Request Accepted'), ('request_updated', 'Request Updated'), ('payment_received', 'Payment Received'), ('work_submitted', 'Work Submitted'), ('revision_requested', 'Revision Requested'), ('work_approved', 'Work Approved'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('message_received', 'New Message'), ('review_received', 'New Review'), ('price_proposed', 'Price Proposal'), ('price_accepted', 'Price Accepted'), ('price_rejected', 'Price Rejected')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_n_user_id_f16910_idx'), models.Index(fields=['user', 'is_read', '-created_at'], name='analytics_n_user_id_424200_idx')],
            },
        ),
    ]
