# Generated by Django 5.2.6 on 2025-11-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deliverable_files',
            field=models.TextField(blank=True, help_text="Professional's deliverable files (JSON)"),
        ),
        migrations.AddField(
            model_name='request',
            name='deliverable_notes',
            field=models.TextField(blank=True, help_text="Professional's notes on deliverables"),
        ),
        migrations.AddField(
            model_name='request',
            name='revision_notes',
            field=models.TextField(blank=True, help_text="Client's revision requests"),
        ),
        migrations.AddField(
            model_name='request',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When professional submitted work', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='attached_files',
            field=models.TextField(blank=True, help_text="Client's initial request files (JSON)"),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
