# Generated by Django 5.2.6 on 2025-11-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_deliverable_files_request_deliverable_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='auto_approve_date',
            field=models.DateTimeField(blank=True, help_text="Date when work will be auto-approved if client doesn't respond", null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='client_initial_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Client's original proposed budget", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='max_revisions',
            field=models.IntegerField(default=3, help_text='Maximum revisions allowed'),
        ),
        migrations.AddField(
            model_name='request',
            name='negotiation_round',
            field=models.IntegerField(default=0, help_text='Current negotiation round (max 5)'),
        ),
        migrations.AddField(
            model_name='request',
            name='price_negotiation_status',
            field=models.CharField(choices=[('none', 'No Negotiation'), ('proposed', 'Professional Proposed Price'), ('counter_offered', 'Client Counter Offered'), ('agreed', 'Price Agreed'), ('cancelled', 'Negotiation Cancelled')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='professional_price_notes',
            field=models.TextField(blank=True, help_text="Professional's explanation for proposed price"),
        ),
        migrations.AddField(
            model_name='request',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='Number of revisions requested'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
    ]
