# Generated by Django 5.2.6 on 2025-11-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_request_auto_approve_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='client_initial_budget',
        ),
        migrations.RemoveField(
            model_name='request',
            name='negotiation_round',
        ),
        migrations.RemoveField(
            model_name='request',
            name='price_negotiation_status',
        ),
        migrations.RemoveField(
            model_name='request',
            name='professional_price_notes',
        ),
    ]
