# Generated by Django 5.2.6 on 2025-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_remove_request_client_initial_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
    ]
