# Generated by Django 5.2.6 on 2025-11-11 07:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0003_request_deliverable_files_request_deliverable_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount paid by client', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text="ProLink's 10% commission", max_digits=10)),
                ('professional_payout', models.DecimalField(decimal_places=2, default=0, help_text='Amount professional receives after fee', max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('escrowed', 'Escrowed'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending_payment', max_length=20)),
                ('payment_method', models.CharField(default='gcash', help_text='Payment method (GCash, etc)', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID (e.g., GCash reference)', max_length=100, null=True, unique=True)),
                ('gcash_number', models.CharField(blank=True, help_text="Client's GCash number", max_length=15)),
                ('gcash_screenshot', models.TextField(blank=True, help_text='Path to payment proof screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When client paid', null=True)),
                ('released_at', models.DateTimeField(blank=True, help_text='When payment released to professional', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for dispute resolution')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='requests.request')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why the dispute was opened')),
                ('client_evidence', models.TextField(blank=True, help_text="Client's evidence/explanation")),
                ('professional_evidence', models.TextField(blank=True, help_text="Professional's evidence/explanation")),
                ('client_files', models.TextField(blank=True, help_text='JSON array of file paths')),
                ('professional_files', models.TextField(blank=True, help_text='JSON array of file paths')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_client', 'Resolved - Favor Client'), ('resolved_professional', 'Resolved - Favor Professional'), ('resolved_partial', 'Resolved - Partial Refund'), ('closed', 'Closed')], default='open', max_length=30)),
                ('resolution_notes', models.TextField(blank=True, help_text="Admin's decision and reasoning")),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded to client (if any)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin who resolved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'ordering': ['-created_at'],
            },
        ),
    ]
