# Generated by Django 5.2.6 on 2025-12-09 03:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_messaging_c_client__8a6e3e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read', 'sender'], name='messaging_m_convers_c07ce8_idx'),
        ),
    ]
